#You should have docker engine version: 18.02.0+
version: '3.6'
services:
  forntend-vuejs:                         #Vue on Frontend
    container_name: forntend-vuejs
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 28882:8080

  backend-server-spring:                #Java with spring-boot API with connection to mongo
    container_name: backend-server-spring
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
    networks:
      - M_TIP_DATABASE

  mongo_db:                         #Mongo as database
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: m_tip_mongo
    restart: unless-stopped
    logging:
      options:
        max-size: 50k
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=haslo
    volumes:
      - ./database:/data
    networks:
      - M_TIP_DATABASE
    command: ["--bind_ip", "0.0.0.0"]

  mongo-client:                    #Mongo Express to better knowledge about data
    image: mongo-express
    container_name: m_tip_client_database
    restart: unless-stopped
    ports:
      - 28881:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=haslo
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - M_TIP_DATABASE

networks:
  M_TIP_DATABASE:
    name: m_tip_database
